name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Pre-installed Node.js
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/frontend
            git pull origin main
            rm -rf .next
            npm install --production
            npm run build --no-lint --no-type-check
            pm2 restart frontend || pm2 start npm --name "frontend" -- run start
          timeout: 60m
